feat(type-expand-provider.ts): expand the tree item only first level
d-kimuson/ts-type-expand pull request #379
Opened 2023-09-08 15:03 UTC by senkenn

#337

2023-09-11 13:41 UTC, d-kimuson requested changes
@senkenn PRありがとうございます！質問とコメントを書いたので確認お願いします！

2023-09-11 13:41 UTC, d-kimuson commented on packages/ts-type-expand/src/vsc/type-expand-provider.ts
> +    this.topElement = undefined
:memo:
- 選択している Node が変わったときに topElement をリセット
- topElement (リセット後初めて getElement で呼ばれたもの) なら展開して topElement 持たせる → 2回目以降は topElement に Elemetn があるので更新されているので折りたたんだ状態に更新して返す

2023-09-11 13:41 UTC, d-kimuson commented on packages/ts-type-expand/src/vsc/type-expand-provider.ts
> +  private topElement?: ExpandableTypeItem
[want] 欲しいのは表示済みかの状態だけなので、boolean で十分で意図が読みやすいかなと思いました！Element 自体持たせている意図が特になければこちらでお願いしたいです！

```suggestion
  private isAlreadyShowTopElement: boolean = false
```

2023-09-11 13:41 UTC, d-kimuson commented on packages/ts-type-expand/src/vsc/type-expand-provider.ts
> +      element.collapsibleState = vscode.TreeItemCollapsibleState.Collapsed
[q] ここの collapsibleState の更新って展開できないものは None、展開できるものは Collapsed で来ると思うので明示的な更新は不要そうに見えたんですが、わかりやすく明示している感じですかね？

2023-09-11 14:09 UTC, d-kimuson commented
この PR に関する Changelog は記入済み
https://github.com/d-kimuson/ts-type-expand/commit/e0ae0781372909429b4f9d4b2c721bbffe47cc7e

Approve 次第取り込んだバージョンをリリースします 🙆‍♂️

2023-09-12 11:42 UTC, senkenn commented on packages/ts-type-expand/src/vsc/type-expand-provider.ts
> +      element.collapsibleState = vscode.TreeItemCollapsibleState.Collapsed
確かに不要ですね。手前の
```ts
    // The bottom layer element is not expandable
    if (element.collapsibleState === vscode.TreeItemCollapsibleState.None) {
      return element
    }
```
も結局「展開できないものは Noneで来る」を前提に条件書いてるのでelseは削除します。

2023-09-14 10:53 UTC, d-kimuson approved these changes
LGTM

2023-09-14 10:53 UTC, merged

2023-09-14 11:14 UTC, d-kimuson commented
@senkenn  PRありがとうございました！
先程この変更を取り込んだ v1.0.6 をリリースしました！
https://github.com/d-kimuson/ts-type-expand/releases/tag/v1.0.6